/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package TestCasePackage;
import java.io.*;
import java.util.LinkedList;
import java.util.StringTokenizer;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import parser.*;
/**
 *
 * @author Prateek
 */
public class DependencyView extends javax.swing.JFrame {

    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	/**
     * Creates new form View
     */
    public DependencyView() throws IOException{
        dependency = new Dependency("src/SourceCode/ClassDiagram.ucls");
        dependentClasses= new LinkedList<String>();
        dependency.getClasses();
	dependency.generateDependencies();
        testCaseFile = new FileReader("src/TestCasePackage/TestCases.txt");
	br = new BufferedReader(testCaseFile);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        classPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        classesComboBox = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        testPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
         jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Select class to which change is made:");

        classesComboBox.setModel(new javax.swing.DefaultComboBoxModel(this.getComboBoxValues()));

       jButton1.setText("Find Dependent Classes");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            @Override
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Find Reduction in Test Effort");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            @Override
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
                    jButton2ActionPerformed(evt);
                } catch (FileNotFoundException ex) {
                    Logger.getLogger(DependencyView.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });

        javax.swing.GroupLayout classPanelLayout = new javax.swing.GroupLayout(classPanel);
        classPanel.setLayout(classPanelLayout);
        classPanelLayout.setHorizontalGroup(
            classPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(classPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(classPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 291, Short.MAX_VALUE)
                    .addGroup(classPanelLayout.createSequentialGroup()
                        .addGroup(classPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(classesComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 197, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        classPanelLayout.setVerticalGroup(
            classPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(classPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(classesComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(60, Short.MAX_VALUE))
        );

        jLabel2.setText("Test Cases:");
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);


        javax.swing.GroupLayout testPanelLayout = new javax.swing.GroupLayout(testPanel);
        testPanel.setLayout(testPanelLayout);
        testPanelLayout.setHorizontalGroup(
            testPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(testPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 271, Short.MAX_VALUE)
       
        );
        testPanelLayout.setVerticalGroup(
            testPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, testPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 327, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(classPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(testPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(testPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(classPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 89, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        try
        {
            changeClass = classesComboBox.getSelectedItem().toString();
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(this, "Select a class to which change is made");
            return;
        }
        changeClass = "SourceCode.".concat(changeClass);
        dependentClasses =  dependency.doBFS(dependency.getIdByClass(changeClass));
        String messageForJOptionPane="";
        Object arr[] = dependentClasses.toArray();
        for(int i=0;i<dependentClasses.size();i++)
        {
            messageForJOptionPane += arr[i].toString()+"\n";
        }
        JOptionPane.showMessageDialog(this, messageForJOptionPane);
	
    }

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) throws FileNotFoundException {
        // TODO add your handling code here:
        try
        {
            changeClass = classesComboBox.getSelectedItem().toString();
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(this, "Select a class to which change is made");
            return;
        }
        changeClass = "SourceCode.".concat(changeClass);
        System.out.println(changeClass);
        dependentClasses =  dependency.doBFS(dependency.getIdByClass(changeClass));
        Object arr[] = dependentClasses.toArray();
        textForTextArea = "";
        countTestCasesRun=countTotalTestCases=0;
        jTextArea1.setText(textForTextArea);
        testCaseFile = new FileReader("src/TestCasePackage/TestCases.txt");
	br = new BufferedReader(testCaseFile);
        try
        {
                while((testCase = br.readLine())!=null)
		{
			StringTokenizer st = new StringTokenizer(testCase,"\t\n ");
			String test = st.nextElement().toString();
			String className = st.nextElement().toString();
                        System.out.println(test+" "+className);
                        int contained=0;
                        for(int i=0;i<dependentClasses.size();i++)
                        {
                            if(className.indexOf(arr[i].toString())!=-1)
                            {
                                contained=1;
                                break;
                            }
                        }
                        if(contained==1)
                        {
                            textForTextArea += "     "+test+"       Running...\n";
                            countTestCasesRun++;
                        }
                        else {
                        textForTextArea += "     "+test+"       Skipping...\n";
                    }
                        countTotalTestCases++;
                        jTextArea1.setText(textForTextArea);
                        
                }
                double reduction = ((double)(countTotalTestCases-countTestCasesRun)/(double)countTotalTestCases)*100;
		System.out.println((int)reduction+"%");
                String messageForJOptionPane="";
                messageForJOptionPane += "Total test cases= "+countTotalTestCases+"\n";
                messageForJOptionPane += "Test Cases that need to re-run= " + countTestCasesRun +"\n";
                messageForJOptionPane += "Total reduction in test effort = "+(int)reduction+"%";
                JOptionPane.showMessageDialog(this, messageForJOptionPane);
        }
        catch(Exception e)
        {
            System.out.println("there");
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (Exception ex) {
            java.util.logging.Logger.getLogger(DependencyView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } 
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                try {
                    new DependencyView().setVisible(true);
                } catch (IOException ex) {
                    Logger.getLogger(DependencyView.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }
    private String[] getComboBoxValues()
    {
        String classArray[] = dependency.getClassArray();
        for(int i=1;i<=dependency.getMaxId();i++)
        {
            classArray[i] = classArray[i].substring(classArray[i].indexOf(".")+1);
        }
        return classArray;
    }
    // Variables declaration - do not modify
    private javax.swing.JComboBox classesComboBox;
    private javax.swing.JLabel jLabel1,jLabel2;
    private javax.swing.JPanel classPanel;
    private javax.swing.JPanel testPanel;
    private String changeClass,testCase;
    private LinkedList<String> dependentClasses;
    private Dependency dependency;
    private FileReader testCaseFile;
    private BufferedReader br;
     private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private String textForTextArea;
    private int countTotalTestCases=0,countTestCasesRun=0;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    
    
    // End of variables declaration
}
